#ifndef BUILD_H_
#define BUILD_H_

#include "enumerators.h"

#define NDIM 3
#define USE_MPI TRUE
#define USE_OMP TRUE
#define USE_GPU TRUE
#define GEOM SPHERICAL
#define EOS COLLAPSE
#define GRAV SPHERICAL_MULTIPOLE_GRAV
#define GR_MONOPOLE TRUE
#define PN_POTENTIAL FALSE
#define USE_EXT_SRC FALSE
#define USE_AUX_SRC FALSE
#define DO_HYDRO TRUE
#define PRINT_OPAC_DATA FALSE
#define DO_RADIATION FALSE
#define PHOTON FALSE
#define NEUTRINO FALSE
#define PERTURB NONE
#define DO_ROTATION FALSE
#define ENFORCE_FLOORS TRUE
#define DENDRITIC_GRID TRUE
#define OUTPUT_PRECISION SINGLE
#define DO_TIMING TRUE
#define DEBUG FALSE
#define POLAR_AVG FALSE
#define USE_FORTRAN_CODE FALSE
#define USE_EXP_INTERP FALSE
#define RAD_CLOSURE M1
#define USE_LARGER_STEP FALSE
#define USE_LINEAR_ALLOCATION TRUE
#define INEL_DT_CONTROL FALSE
#define RCOORD SINH_MODIFIED
#define THCOORD POLYTH

#define BUILD_STRING "This Fornax executable was built with the below options:\\nNDIM=3\\nUSE_MPI=TRUE\\nUSE_OMP=TRUE\\nUSE_GPU=TRUE\\nGEOM=SPHERICAL\\nEOS=COLLAPSE\\nGRAV=SPHERICAL_MULTIPOLE_GRAV\\nGR_MONOPOLE=TRUE\\nPN_POTENTIAL=FALSE\\nUSE_EXT_SRC=FALSE\\nUSE_AUX_SRC=FALSE\\nDO_HYDRO=TRUE\\nPRINT_OPAC_DATA=FALSE\\nDO_RADIATION=FALSE\\nPHOTON=FALSE\\nNEUTRINO=FALSE\\nPERTURB=NONE\\nDO_ROTATION=FALSE\\nENFORCE_FLOORS=TRUE\\nDENDRITIC_GRID=TRUE\\nOUTPUT_PRECISION=SINGLE\\nDO_TIMING=TRUE\\nDEBUG=FALSE\\nPOLAR_AVG=FALSE\\nUSE_FORTRAN_CODE=FALSE\\nUSE_EXP_INTERP=FALSE\\nRAD_CLOSURE=M1\\nUSE_LARGER_STEP=FALSE\\nUSE_LINEAR_ALLOCATION=TRUE\\nINEL_DT_CONTROL=FALSE\\nRCOORD=SINH_MODIFIED\\nTHCOORD=POLYTH\\n"
#endif // BUILD_H_

