#ifndef BUILD_H_
#define BUILD_H_

#include "enumerators.h"

#define NDIM 1
#define USE_MPI TRUE
#define USE_OMP FALSE
#define GEOM SPHERICAL
#define EOS COLLAPSE
#define GRAV SPHERICAL_MONOPOLE_GRAV
#define GR_MONOPOLE FALSE
#define PN_POTENTIAL FALSE
#define USE_EXT_SRC TRUE
#define USE_AUX_SRC TRUE
#define DO_HYDRO TRUE
#define PRINT_OPAC_DATA FALSE
#define DO_RADIATION FALSE
#define PHOTON FALSE
#define NEUTRINO FALSE
#define PERTURB NONE
#define DO_ROTATION FALSE
#define ENFORCE_FLOORS TRUE
#define DENDRITIC_GRID FALSE
#define OUTPUT_PRECISION SINGLE
#define DO_TIMING TRUE
#define DEBUG FALSE
#define POLAR_AVG FALSE
#define USE_FORTRAN_CODE FALSE
#define USE_EXP_INTERP FALSE
#define RAD_CLOSURE M1
#define USE_LARGER_STEP FALSE
#define USE_LINEAR_ALLOCATION TRUE
#define INEL_DT_CONTROL FALSE
#define RCOORD SINH_MODIFIED
#define THCOORD POLYTH

#define BUILD_STRING \
"This Fornax executable was built with the below options:\n\
NDIM=1\n\
USE_MPI=TRUE\n\
USE_OMP=FALSE\n\
GEOM=SPHERICAL\n\
EOS=COLLAPSE\n\
GRAV=SPHERICAL_MONOPOLE_GRAV\n\
GR_MONOPOLE=FALSE\n\
PN_POTENTIAL=FALSE\n\
USE_EXT_SRC=TRUE\n\
USE_AUX_SRC=TRUE\n\
DO_HYDRO=TRUE\n\
PRINT_OPAC_DATA=FALSE\n\
DO_RADIATION=FALSE\n\
PHOTON=FALSE\n\
NEUTRINO=FALSE\n\
PERTURB=NONE\n\
DO_ROTATION=FALSE\n\
ENFORCE_FLOORS=TRUE\n\
DENDRITIC_GRID=FALSE\n\
OUTPUT_PRECISION=SINGLE\n\
DO_TIMING=TRUE\n\
DEBUG=FALSE\n\
POLAR_AVG=FALSE\n\
USE_FORTRAN_CODE=FALSE\n\
USE_EXP_INTERP=FALSE\n\
RAD_CLOSURE=M1\n\
USE_LARGER_STEP=FALSE\n\
USE_LINEAR_ALLOCATION=TRUE\n\
INEL_DT_CONTROL=FALSE\n\
RCOORD=SINH_MODIFIED\n\
THCOORD=POLYTH\n\
"

#endif // BUILD_H_

